CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  timezone TEXT NOT NULL,
  festival_name TEXT NOT NULL,
  festival_short_name TEXT NOT NULL,
  network_name TEXT NOT NULL,
  network_short_name TEXT NOT NULL,
  show_name TEXT NOT NULL,
  theme_json JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(theme_json)='object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO events(
  id,slug,status,timezone,festival_name,festival_short_name,
  network_name,network_short_name,show_name,theme_json
) VALUES (
  1,'as-above-so-below','active','America/New_York','As Above So Below','AASB',
  'Fried Rice News Network','FRNN','Fried News',
  '{"background":"#050408","panel":"#0c0810","ink":"#f3e8d2","accent":"#ff3eb5","secondary":"#53e7ff","highlight":"#c9ff3f","muted":"#a699a9"}'::jsonb
) ON CONFLICT (id) DO NOTHING;

DO $$
DECLARE
  table_name TEXT;
  constraint_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'access_codes','players','visits','video_answers','final_reflections',
    'quick_start_claims','player_profiles','player_profile_versions','app_settings','prize_draws'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS event_id BIGINT', table_name);
    EXECUTE format('UPDATE %I SET event_id=1 WHERE event_id IS NULL', table_name);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN event_id SET DEFAULT 1', table_name);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN event_id SET NOT NULL', table_name);
    constraint_name := table_name || '_event_id_fkey';
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname=constraint_name) THEN
      EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY(event_id) REFERENCES events(id)',
        table_name, constraint_name
      );
    END IF;
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS access_codes_event_idx ON access_codes(event_id,code);
CREATE INDEX IF NOT EXISTS players_event_idx ON players(event_id,code);
CREATE INDEX IF NOT EXISTS visits_event_idx ON visits(event_id,code);
CREATE INDEX IF NOT EXISTS video_answers_event_idx ON video_answers(event_id,code);
CREATE INDEX IF NOT EXISTS final_reflections_event_idx ON final_reflections(event_id,code);
CREATE INDEX IF NOT EXISTS quick_start_claims_event_idx ON quick_start_claims(event_id,token_hash);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM player_profiles
    WHERE BTRIM(display_name) <> ''
    GROUP BY event_id, LOWER(REGEXP_REPLACE(BTRIM(display_name), '[[:space:]]+', ' ', 'g'))
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'FRNN migration stopped: duplicate normalized player names require operator review';
  END IF;
END $$;

ALTER TABLE player_profiles
  ADD COLUMN IF NOT EXISTS normalized_display_name TEXT
  GENERATED ALWAYS AS (
    LOWER(REGEXP_REPLACE(BTRIM(display_name), '[[:space:]]+', ' ', 'g'))
  ) STORED;

CREATE UNIQUE INDEX IF NOT EXISTS player_profiles_event_display_name_unique
  ON player_profiles(event_id,normalized_display_name)
  WHERE normalized_display_name <> '';

CREATE INDEX IF NOT EXISTS player_profiles_event_name_search_idx
  ON player_profiles(event_id,normalized_display_name);

SELECT setval(
  pg_get_serial_sequence('events','id'),
  GREATEST((SELECT COALESCE(MAX(id),1) FROM events),1),
  TRUE
);
