DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM broadcast_clock
    WHERE singleton = TRUE
      AND started_at IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'BCL_MIGRATION_REQUIRES_OFF_AIR';
  END IF;
END
$$;

CREATE SEQUENCE IF NOT EXISTS broadcast_run_id_seq AS BIGINT START WITH 1;

CREATE TABLE IF NOT EXISTS broadcast_packaged_items (
  id TEXT PRIMARY KEY,
  definition_version BIGINT NOT NULL DEFAULT 1 CHECK (definition_version > 0),
  title TEXT NOT NULL CHECK (BTRIM(title) <> ''),
  item_kind TEXT NOT NULL CHECK (item_kind IN ('PROGRAM','TRANSITION')),
  playback_type TEXT NOT NULL CHECK (playback_type IN ('test_card','image','video')),
  media_ref TEXT,
  duration_ms BIGINT NOT NULL CHECK (duration_ms > 0),
  loop_eligible BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CHECK (playback_type = 'test_card' OR NULLIF(BTRIM(media_ref), '') IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS broadcast_queue_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  packaged_item_id TEXT NOT NULL REFERENCES broadcast_packaged_items(id) ON DELETE RESTRICT,
  queue_position INTEGER NOT NULL CHECK (queue_position > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT broadcast_queue_entries_queue_position_key
    UNIQUE (queue_position) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS broadcast_active_run (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  run_id BIGINT UNIQUE,
  packaged_item_id TEXT REFERENCES broadcast_packaged_items(id) ON DELETE RESTRICT,
  source_definition_version BIGINT CHECK (source_definition_version > 0),
  source_queue_entry_id BIGINT,
  source_queue_position INTEGER CHECK (source_queue_position > 0),
  title TEXT,
  item_kind TEXT CHECK (item_kind IN ('PROGRAM','TRANSITION')),
  playback_type TEXT CHECK (playback_type IN ('test_card','image','video')),
  media_ref TEXT,
  duration_ms BIGINT CHECK (duration_ms > 0),
  started_at TIMESTAMPTZ,
  CHECK (playback_type IS NULL OR playback_type = 'test_card' OR NULLIF(BTRIM(media_ref), '') IS NOT NULL),
  CHECK (
    (
      run_id IS NULL
      AND packaged_item_id IS NULL
      AND source_definition_version IS NULL
      AND source_queue_entry_id IS NULL
      AND source_queue_position IS NULL
      AND title IS NULL
      AND item_kind IS NULL
      AND playback_type IS NULL
      AND media_ref IS NULL
      AND duration_ms IS NULL
      AND started_at IS NULL
    )
    OR
    (
      run_id IS NOT NULL
      AND packaged_item_id IS NOT NULL
      AND source_definition_version IS NOT NULL
      AND source_queue_entry_id IS NOT NULL
      AND source_queue_position IS NOT NULL
      AND title IS NOT NULL
      AND item_kind IS NOT NULL
      AND playback_type IS NOT NULL
      AND duration_ms IS NOT NULL
      AND started_at IS NOT NULL
    )
  )
);

INSERT INTO broadcast_active_run(singleton)
VALUES (TRUE)
ON CONFLICT (singleton) DO NOTHING;

INSERT INTO broadcast_packaged_items(
  id,
  definition_version,
  title,
  item_kind,
  playback_type,
  media_ref,
  duration_ms,
  loop_eligible
)
SELECT
  id,
  1,
  title,
  'PROGRAM',
  program_type,
  media_ref,
  duration_ms,
  FALSE
FROM broadcast_programs
ON CONFLICT (id) DO NOTHING;

INSERT INTO broadcast_queue_entries(packaged_item_id,queue_position)
SELECT id,ROW_NUMBER() OVER (ORDER BY queue_position,id)::INTEGER
FROM broadcast_programs
WHERE NOT EXISTS (SELECT 1 FROM broadcast_queue_entries)
ORDER BY queue_position,id;
